#
# Copyright 2017 Alexander Orlov <alexander.orlov@loxal.net>. All rights reserved.
#

server:
  port: 8200

vault:
  uri: http://${couchbase.cluster.ip}:8200
  token: ${random.uuid} # introduce valid (root) token in your local configuration

spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  application:
    name: quizzer
  data:
    cassandra:
      keyspace-name: ${couchbase.cluster.bucket}
      contact-points: ${couchbase.cluster.ip}

couchbase:
  cluster:
    ip: sky.loxal.net
    bucket: ${spring.application.name}
    password: ${security.user.password}
